title: "IPinator for OS X"
description: "Glanceable IP Address Geocoding for OS X"
tagline: "IP Widget for OS X Yosemite"
keywords: [ip address, widget, notification center widget, external ip, ip extension, network, geolocation, ip geocoding, vpn, osx, mac, yosemite]
author:
  name: "Reda Lemeden"

baseurl: ""
url: http://ipinator.kaishin.co
future: false
show_drafts: false
gems:
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [
  "node_modules",
  "gulp.js",
  "gulpfile.coffee",
  "package.json",
  "README.md",
  "Gemfile",
  "Gemfile.lock"
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
